version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: admin_service
    ports:
      - "3999:3999"
    volumes:
      - ./api:/app
    networks:
      - app-network
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb+srv://dinithineranjana:dnt123@bakery-shop.ytbrm.mongodb.net/?retryWrites=true&w=majority&appName=Bakery-Shop
    depends_on:
      - mongo_admin
    restart: unless-stopped

  mongo_admin:
    image: mongo
    container_name: mongo_admin
    ports:
      - "27018:27017"  
    volumes:
      - mongo-data-admin:/data/db
    networks:
      - app-network

volumes:
  mongo-data-admin:

networks:
  app-network:
    driver: bridge
