apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: bakery-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:  
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: sanjananimesh/frontend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
       