apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: bakery-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: user-service:latest
        ports:
        - containerPort: 4000
        env:
        - name: PORT
          value: "4000"
        - name: NODE_ENV
          value: "development"
        - name: ALLOWED_ORIGINS
          value: "http://localhost:8080,http://localhost,http://frontend"