apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: bakery-shop
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80           # External port
      targetPort: 3000   # Matches container port
  type: LoadBalancer