apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: bakery-shop
spec:
  type: NodePort
  selector:
    app: user-service
  ports:
    - name: http
      protocol: TCP
      port: 4000
      targetPort: 4000
      nodePort: 32608