apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-user
  namespace: bakery-shop
spec:
  serviceName: mongo-user
  replicas: 1
  selector:
    matchLabels:
      app: mongo-user
  template:
    metadata:
      labels:
        app: mongo-user
    spec:
      containers:
      - name: mongo
        image: mongo:latest
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-data-user
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongo-data-user
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-user
  namespace: bakery-shop
spec:
  selector:
    app: mongo-user
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017